[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

[workspace]
members=[
  "client",
  "server",
  "crates/messages"
, "crates/logging"]

[dependencies]
messages = { path = "crates/messages", version = "0.1.0" }
logging = { path = "crates/logging", version = "0.1.0" }


